baseurl = "https://jaredvacanti.com/"
languageCode = "en-us"
title = "Jared Vacanti's Homepage"
#theme = "hugo-creative-portfolio-theme"

# Enable comments by entering your Disqus shortname
disqusShortname = "jaredvacanti"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-50805903-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "the online homepage of Jared Vacanti"
 
  sidebarAbout = [
    "I'm a financial data scientist , I work primarily in Python and C/C++.",
    "I wrote software that uses some speedy assumtions on a local volatility model to trade equity index options and the short end of the yield curve (Eurodollars).",
    "Originally from Nebraska, currently in Chicago, Illinois."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "jared@jaredvacanti.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Code"
  url = "https://code.jaredvacanti.com"
  
  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"




  [params.social]
  email         = "jared@jaredvacanti.com"
  twitter       = "https://twitter.com/jaredvacanti"
  github        = "https://github.com/jaredvacanti"
  stackoverflow = "https://stackexchange.com/users/1694559/jared"
