backend:
  name: github
  repo: jaredvacanti/jared-dot-com
  branch: master
  site_domain: gifted-wilson-9b7144.netlify.com
  
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:

  - name: "post"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt text", name: "imageAlt", widget: "string"}
      - {label: "Image caption", name: "imageCap", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}

  - name: "trade"
    label: "Trade"
    folder: "content/trades"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Trade Closed?", name: "closed", widget: "boolean", default: false}
      - {label: "Closing Price", name: "closed_price", widget: "string"}
      - {label: "Entry Price", name: "price", widget: "string"}
      - {label: "publishdatetest", name: "publishdatetest", widget: "boolean", default: false}
